server:
  port: ${PORT:8863}
#eureka:
#  client:
#    register-with-eureka: false
#    serviceurl: defaultZone=http://localhost:8850/eureka/
eureka:
  client:
    register-with-eureka: true
    #fetch-registry: false
    serviceurl:
      defaultZone: http://localhost:8850/eureka/
message: Configuracion de Cajero en el servidor levantado!
spring:
  application:
    name: ms_cajero
